# Generated by Django 2.2.10 on 2020-11-27 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerForAskWithMultipleAnswers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300, verbose_name='Ответ на вопрос')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'ответ на вопрос с множеством ответов',
                'verbose_name_plural': 'ответы на вопрос с множеством ответов',
                'db_table': 'answers_to_ask_with_multiple_answers',
            },
        ),
        migrations.CreateModel(
            name='AnswerForAskWithOneAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300, verbose_name='Ответ на вопрос')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'ответ на вопрос с одним ответом',
                'verbose_name_plural': 'ответы на вопрос с одним ответом',
                'db_table': 'answers_to_ask_with_one_answer',
            },
        ),
        migrations.CreateModel(
            name='Interrogation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=300, unique=True, verbose_name='Название опроса')),
                ('active', models.BooleanField(default=False, verbose_name='Активен')),
                ('date_begin', models.DateField(verbose_name='Дата начала')),
                ('date_end', models.DateField(verbose_name='Дата окончания')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'опрос',
                'verbose_name_plural': 'опросы',
                'db_table': 'interrogation',
                'ordering': ('creation_date', 'date_begin', 'date_end'),
            },
        ),
        migrations.CreateModel(
            name='AskWithTextAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст вопроса')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('interrogation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Interrogation', verbose_name='опрос')),
            ],
            options={
                'verbose_name': 'вопрос с текстовым ответом',
                'verbose_name_plural': 'вопросы с текстовым ответом',
                'db_table': 'asks_with_text_answer',
                'ordering': ('creation_date',),
            },
        ),
        migrations.CreateModel(
            name='AskWithOneAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст вопроса')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('interrogation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Interrogation', verbose_name='опрос')),
            ],
            options={
                'verbose_name': 'вопрос с одним правильным ответом',
                'verbose_name_plural': 'вопросы с одним правильным ответом',
                'db_table': 'asks_with_one_answer',
                'ordering': ('creation_date',),
            },
        ),
        migrations.CreateModel(
            name='AskWithMultipleAnswers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст вопроса')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('interrogation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Interrogation', verbose_name='опрос')),
            ],
            options={
                'verbose_name': 'вопрос с множеством ответов',
                'verbose_name_plural': 'вопросы с множеством ответов',
                'db_table': 'asks_with_multiple_answers',
                'ordering': ('creation_date',),
            },
        ),
    ]
