# Generated by Django 2.2.10 on 2020-11-30 07:00

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20201127_2114'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='interrogation',
            managers=[
                ('only_active', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='interrogation',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание опроса.'),
        ),
    ]
