# Generated by Django 2.2.10 on 2020-11-30 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20201130_1000'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTextAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField()),
            ],
            options={
                'verbose_name': 'текстовый ответ пользователя',
                'verbose_name_plural': 'текстовые ответы пользователя',
                'db_table': 'user_text_answers',
            },
        ),
        migrations.CreateModel(
            name='UserAnswersForAskWithOneAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.AnswerForAskWithOneAnswer')),
            ],
            options={
                'verbose_name': 'ответ пользователя на вопрос с одним ответом',
                'verbose_name_plural': 'ответы пользователя на вопросы с одним ответом',
                'db_table': 'user_single_answers',
            },
        ),
        migrations.CreateModel(
            name='UserAnswersForAskWithMultipleAnswers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.AnswerForAskWithMultipleAnswers')),
            ],
            options={
                'verbose_name': 'ответ пользователя на вопрос с множеством ответов',
                'db_table': 'user_multi_answers',
            },
        ),
    ]
