# Generated by Django 2.2.10 on 2020-11-30 11:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0004_useranswersforaskwithmultipleanswers_useranswersforaskwithoneanswer_usertextanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='useranswersforaskwithmultipleanswers',
            name='anonymous_user_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='id анонимного пользователя'),
        ),
        migrations.AddField(
            model_name='useranswersforaskwithmultipleanswers',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='useranswersforaskwithoneanswer',
            name='anonymous_user_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='id анонимного пользователя'),
        ),
        migrations.AddField(
            model_name='useranswersforaskwithoneanswer',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='usertextanswer',
            name='anonymous_user_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='id анонимного пользователя'),
        ),
        migrations.AddField(
            model_name='usertextanswer',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.RemoveField(
            model_name='useranswersforaskwithmultipleanswers',
            name='answers',
        ),
        migrations.AddField(
            model_name='useranswersforaskwithmultipleanswers',
            name='answers',
            field=models.ManyToManyField(to='core.AnswerForAskWithMultipleAnswers'),
        ),
    ]
